### ISSUE TITLE
Register this package?

### ISSUE THREAD

**Issue by eschnett** [eschnett/SixelTerm.jl#3]
Is this package still maintained? Is there another, registered package that I should be using instead? Otherwise, would you want to registers this package with the Julia registry?

**Comment by eschnett** [comment]
I'm using it, and it works for me. I'd be happy to maintain it.

**Comment by tshort** [comment]
Great, @eschnett. I'm happy to transfer the repo to you if you want.

**Comment by eschnett** [comment]
Thank you. How does this work?

**Comment by tshort** [comment]
Under the repo settings under "Danger Zone", there's an option to "Transfer repository". You should have a request now.

**Comment by eschnett** [comment]
Thank you! The transfer worked fine.
